# Generated by Django 5.1.2 on 2024-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("blog_text", models.TextField(verbose_name="Содержимое статьи")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/blog", verbose_name="Превью (изображение)"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубиковать")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Статью",
                "verbose_name_plural": "Статьи",
                "ordering": ["title", "created_at"],
            },
        ),
    ]
