# Generated by Django 5.1.2 on 2024-11-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("image", models.ImageField(upload_to="images/", verbose_name="Изображение")),
                ("price", models.FloatField(verbose_name="Цена за единицу")),
                ("created_at", models.DateField(auto_now=True, verbose_name="Дата создания")),
                ("updated_at", models.DateField(verbose_name="Дата изменения")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=models.SET("Категория не указана"),
                        related_name="category",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "price", "created_at"],
            },
        ),
    ]
